[package]
name = "minecraft-rcon-cli"
version = "0.1.0"
edition = "2021"

description = "A Rust-based Minecraft RCON CLI with rustyline autocompletion."

[dependencies]
minecraft-client-rs = "0.1"
rustyline = "15.0"
anyhow = "1.0"

[profile.release]
lto = true
